import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Supported languages
export type Language = 'en' | 'fr' | 'es' | 'it' | 'de' | 'zh';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
];

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Auth
    'login.title': 'Sign In',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign Up',
    'login.subtitle': 'Free House Music Promo Pool',
    
    // Signup
    'signup.welcome': 'Welcome to SPYNNERS!',
    'signup.joinCommunity': 'Join the largest community of House Music DJs and producers',
    'signup.youAre': 'You are...',
    'signup.continue': 'Continue',
    'signup.createAccount': 'Create your account',
    'signup.fillInfo': 'Fill in your information to join SPYNNERS',
    'signup.fullName': 'Full name / Artist name',
    'signup.labelName': 'Label name',
    'signup.confirmPassword': 'Confirm password',
    'signup.acceptTerms': 'I accept the',
    'signup.termsOfUse': 'terms of use',
    'signup.and': 'and',
    'signup.privacyPolicy': 'privacy policy',
    'signup.createMyAccount': 'Create my account',
    'signup.alreadyAccount': 'Already have an account?',
    'signup.change': 'Change',
    
    // User types
    'userType.dj': 'DJ',
    'userType.djDesc': 'I play music at clubs/events',
    'userType.producer': 'Producer',
    'userType.producerDesc': 'I produce music',
    'userType.djProducer': 'DJ & Producer',
    'userType.djProducerDesc': 'I play and produce',
    'userType.label': 'Label',
    'userType.labelDesc': 'I represent a music label',
    
    // Navigation
    'nav.home': 'Home',
    'nav.library': 'My Uploads',
    'nav.playlist': 'Playlists',
    'nav.received': 'Received',
    'nav.spyn': 'SPYN',
    'nav.chat': 'Chat',
    'nav.profile': 'Profile',
    'nav.upload': 'Upload Track',
    
    // Page titles
    'page.myUploads': 'My Uploads',
    'page.myPlaylists': 'My Playlists', 
    'page.receivedTracks': 'Received Tracks',
    'page.chat': 'Messages',
    'page.uploadTrack': 'Upload Track',
    'page.noTracks': 'No tracks yet',
    'page.noPlaylists': 'No playlists yet',
    'page.noReceivedTracks': 'No received tracks',
    'page.createPlaylist': 'Create Playlist',
    'page.playlistName': 'Playlist Name',
    'page.createPlaylistHint': 'Create your first playlist to organize your favorite tracks',
    
    // Upload
    'upload.selectAudio': 'Select MP3 or WAV file',
    'upload.selectCover': 'Tap to select cover art',
    'upload.coverExtracted': 'Cover art extracted from MP3',
    'upload.submit': 'Upload Track',
    'upload.uploading': 'Uploading...',
    'upload.success': 'Track uploaded successfully!',
    'upload.error': 'Upload failed',
    'upload.shareMusic': 'Share your music with the SPYNNERS community',
    'upload.uploadFor': 'Upload for account of...',
    'upload.searchProducer': 'Search producer or label...',
    'upload.coverImage': 'Cover Image',
    'upload.squareFormat': 'Square format recommended (1:1)',
    'upload.audioFile': 'Audio File',
    'upload.trackInfo': 'Track Information',
    'upload.title': 'Title',
    'upload.artistName': 'Artist Name',
    'upload.labelName': 'Label Name',
    'upload.collaborators': 'Collaborators',
    'upload.genreTech': 'Genre & Technical',
    'upload.genre': 'Genre',
    'upload.selectGenre': 'Select genre',
    'upload.bpm': 'BPM',
    'upload.key': 'Key',
    'upload.energyLevel': 'Energy Level',
    'upload.mood': 'Mood',
    'upload.additionalInfo': 'Additional Information',
    'upload.releaseDate': 'Release Date',
    'upload.description': 'Description',
    'upload.options': 'Options',
    'upload.unreleased': 'Unreleased Track',
    'upload.unreleasedDesc': 'This track hasn\'t been released yet',
    'upload.vipRequest': 'V.I.P. Track Request',
    'upload.vipRequestDesc': 'Request to add this track to V.I.P. collection',
    'upload.legalAgreements': 'Legal Agreements',
    'upload.rightsConfirm': 'I confirm that I own or have the rights to upload this track',
    'upload.freeDownload': 'I authorize free download for promotional purposes on SPYNNERS',
    'upload.firstTrackHint': 'Upload your first track to get started',
    
    // SPYN
    'spyn.detection': 'DETECTION',
    'spyn.recordSet': 'RECORD SET',
    'spyn.micro': 'Micro',
    'spyn.usbRec': 'USB + Rec',
    'spyn.analyzing': 'Analyzing with ACRCloud...',
    'spyn.listening': 'Listening... (10s)',
    'spyn.trackIdentified': 'Track Identified!',
    'spyn.newSearch': 'New Search',
    'spyn.djSetStarted': 'DJ Set Started',
    'spyn.djSetEnded': 'DJ Set Ended',
    'spyn.tracksIdentified': 'Tracks identified',
    'spyn.save': 'Save',
    'spyn.delete': 'Delete',
    'spyn.stop': 'Stop',
    'spyn.stopRecording': 'Stop Recording',
    'spyn.producerNotified': 'Producer Notified!',
    'spyn.playingTrack': 'has been notified that you\'re playing their track!',
    'spyn.djSetComplete': 'DJ Set Complete',
    'spyn.duration': 'Duration',
    
    // Profile
    'profile.editProfile': 'Edit Profile',
    'profile.blackDiamonds': 'Black Diamonds',
    'profile.settings': 'Settings',
    'profile.help': 'Help & Support',
    'profile.terms': 'Terms & Privacy',
    'profile.admin': 'Admin Panel',
    'profile.logout': 'Log Out',
    'profile.updateInfo': 'Update your information',
    'profile.buyDiamonds': 'Buy diamonds',
    'profile.manageTracks': 'Manage your tracks',
    'profile.viewPlaylists': 'View your playlists',
    'profile.visitWebsite': 'Visit spynners.com',
    'profile.frequentQuestions': 'Frequently asked questions',
    'profile.termsOfUse': 'Terms of use',
    'profile.uploads': 'Uploads',
    'profile.diamonds': 'Diamonds',
    'profile.favorites': 'Favorites',
    'profile.logoutConfirm': 'Do you really want to log out?',
    
    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search',
    'common.noResults': 'No results',
    'common.language': 'Language',
    'common.selectLanguage': 'Select your language',
    'common.tracks': 'tracks',
    'common.members': 'Members',
    'common.online': 'Online',
    'common.unread': 'Unread',
    'common.playAll': 'Play All',
    'common.shuffle': 'Shuffle',
    'common.select': 'Select',
    
    // Menu items
    'menu.myUploads': 'My Uploads',
    'menu.profile': 'Profile',
    'menu.chat': 'Chat',
    'menu.received': 'Received',
    'menu.playlists': 'Playlists',
    'menu.analytics': 'Analytics',
    'menu.rankings': 'Rankings',
    'menu.liveRadar': 'Live Radar',
    'menu.vip': 'V.I.P.',
    'menu.uploadTrack': 'Upload Track',
    'menu.website': 'Website',
    
    // Actions
    'action.download': 'Download',
    'action.share': 'Share',
    'action.addToPlaylist': 'Add to Playlist',
    'action.sendTrack': 'Send Track',
    
    // Filters
    'filter.allGenres': 'All Genres',
    'filter.allEnergy': 'All Energy Levels',
    'filter.recentlyAdded': 'Recently Added',
    'filter.aToZ': 'A to Z',
    'filter.topRated': 'Top Rated',
    'filter.low': 'Low',
    'filter.medium': 'Medium',
    'filter.high': 'High',
    'filter.vipOnly': 'VIP Only',
    'filter.searchPlaceholder': 'Search tracks...',
    
    // Chat
    'chat.messages': 'Messages',
    'chat.searchMembers': 'Search members...',
    'chat.noMembersFound': 'No members found',
    'chat.loadingMembers': 'Loading members...',
    'chat.noMessages': 'No messages yet',
    'chat.startConversation': 'Say hello to start the conversation!',
    'chat.typeMessage': 'Type a message...',
    
    // Playlist
    'playlist.tracks': 'Tracks',
    'playlist.noTracksInPlaylist': 'No tracks in this playlist',
    'playlist.addTracksHint': 'Add tracks from the home screen',
    'playlist.loadingTracks': 'Loading tracks...',
    
    // Library
    'library.myUploads': 'My Uploads',
    'library.noUploads': 'No uploads yet',
    'library.uploadFirst': 'Upload your first track to get started',
    'library.status': 'Status',
    'library.pending': 'Pending',
    'library.approved': 'Approved',
    'library.rejected': 'Rejected',
    
    // Received
    'received.title': 'Received Tracks',
    'received.from': 'From',
    'received.noTracks': 'No tracks received yet',
    'received.waitingTracks': 'Tracks sent to you will appear here',
    
    // Diamonds
    'diamonds.yourBalance': 'Your balance',
    'diamonds.info': 'Black Diamonds allow downloading exclusive VIP tracks and accessing premium content.',
    'diamonds.buyDiamonds': 'Buy Diamonds',
    'diamonds.popular': 'POPULAR',
    'diamonds.processing': 'Processing...',
    'diamonds.buyNow': 'Buy Now',
    'diamonds.vipBenefits': 'VIP Benefits',
    'diamonds.vipDownloads': 'VIP Downloads',
    'diamonds.accessExclusive': 'Access exclusive tracks',
    'diamonds.premiumContent': 'Premium Content',
    'diamonds.tracksBeforeEveryone': 'Tracks before everyone',
    'diamonds.supportArtists': 'Support Artists',
    'diamonds.supportProducers': 'Support producers',
    'diamonds.selectionRequired': 'Selection required',
    'diamonds.chooseAPack': 'Choose a diamond pack',
    'diamonds.confirmPurchase': 'Buy {amount} Black Diamonds for {price}?\n\nYou will be redirected to spynners.com to complete the purchase.',
    'diamonds.purchaseComplete': 'Purchase Complete! 💎',
    'diamonds.diamondsAdded': '{amount} Black Diamonds added to your account!',
    'diamonds.purchaseError': 'Could not open purchase page. Please try again.',
    'diamonds.continue': 'Continue',
    
    // Analytics
    'analytics.title': 'My Analytics',
    'analytics.noTracks': 'No tracks yet',
    'analytics.uploadToSee': 'Upload tracks to see your analytics',
    'analytics.myTracks': 'My Tracks',
    'analytics.totalPlays': 'Total Plays',
    'analytics.downloads': 'Downloads',
    'analytics.avgRating': 'Avg. Rating',
    'analytics.trackStatus': 'Track Status',
    'analytics.approved': 'Approved',
    'analytics.pending': 'Pending',
    
    // Edit Profile
    'edit.title': 'Edit Profile',
    'edit.iAmA': 'I am a...',
    'edit.dj': 'DJ',
    'edit.producer': 'Producer',
    'edit.both': 'Both',
    'edit.label': 'Label',
    'edit.musicLover': 'Music Lover',
    'edit.basicInfo': 'Basic Information',
    'edit.fullName': 'Full Name',
    'edit.djName': 'DJ Name',
    'edit.producerName': 'Producer Name',
    'edit.sacemNumber': 'SACEM Member Number (optional)',
    'edit.socialLinks': 'Social Links',
    'edit.saveChanges': 'Save Changes',
    'edit.saving': 'Saving...',
    
    // Help/FAQ
    'help.title': 'Help & FAQ',
    'help.frequentQuestions': 'Frequently Asked Questions',
    'help.howToDownload': 'How to download a track?',
    'help.whatAreDiamonds': 'What are Black Diamonds?',
    'help.howToUpload': 'How to upload a track?',
    'help.howSpynWorks': 'How does SPYN work?',
    'help.canCreatePlaylists': 'Can I create multiple playlists?',
    'help.howToBecomeProducer': 'How to become a producer on SPYNNERS?',
    'help.areTracksFree': 'Are tracks free?',
    'help.contactUs': 'Contact Us',
    'help.haveQuestion': 'Have a question?',
    'help.writeMessage': 'Write your message here...',
    'help.send': 'Send',
    
    // Terms
    'terms.title': 'Terms of Use',
    'terms.lastUpdate': 'Last update',
    'terms.acceptConditions': 'Acceptance of conditions',
    'terms.serviceDescription': 'Description of service',
    'terms.userAccount': 'User account',
    'terms.userContent': 'User content',
    'terms.blackDiamonds': 'Black Diamonds',
    
    // Live Radar
    'radar.title': 'Live Radar',
    'radar.activeDjs': 'Active DJs',
    'radar.nearYou': 'Near you',
    'radar.worldwide': 'Worldwide',
    'radar.noDjsNearby': 'No DJs nearby',
    'radar.expandSearch': 'Expand your search to find more DJs',
    'radar.playing': 'Playing',
    'radar.distance': 'Distance',
  },
  
  fr: {
    // Auth
    'login.title': 'Connexion',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.forgotPassword': 'Mot de passe oublié ?',
    'login.signIn': 'Se connecter',
    'login.noAccount': "Pas encore de compte ?",
    'login.signUp': "S'inscrire",
    'login.subtitle': 'Free House Music Promo Pool',
    
    // Signup
    'signup.welcome': 'Bienvenue sur SPYNNERS!',
    'signup.joinCommunity': 'Rejoignez la plus grande communauté de DJs et producteurs House Music',
    'signup.youAre': 'Vous êtes...',
    'signup.continue': 'Continuer',
    'signup.createAccount': 'Créer votre compte',
    'signup.fillInfo': 'Remplissez vos informations pour rejoindre SPYNNERS',
    'signup.fullName': 'Nom complet / Nom d\'artiste',
    'signup.labelName': 'Nom du label',
    'signup.confirmPassword': 'Confirmer le mot de passe',
    'signup.acceptTerms': 'J\'accepte les',
    'signup.termsOfUse': 'conditions d\'utilisation',
    'signup.and': 'et la',
    'signup.privacyPolicy': 'politique de confidentialité',
    'signup.createMyAccount': 'Créer mon compte',
    'signup.alreadyAccount': 'Déjà un compte ?',
    'signup.change': 'Modifier',
    
    // User types
    'userType.dj': 'DJ',
    'userType.djDesc': 'Je joue de la musique en club/événements',
    'userType.producer': 'Producteur',
    'userType.producerDesc': 'Je produis de la musique',
    'userType.djProducer': 'DJ & Producteur',
    'userType.djProducerDesc': 'Je joue et produis',
    'userType.label': 'Label',
    'userType.labelDesc': 'Je représente un label musical',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.library': 'Mes Uploads',
    'nav.playlist': 'Playlists',
    'nav.received': 'Reçus',
    'nav.spyn': 'SPYN',
    'nav.chat': 'Chat',
    'nav.profile': 'Profil',
    'nav.upload': 'Uploader un Track',
    
    // Page titles
    'page.myUploads': 'Mes Uploads',
    'page.myPlaylists': 'Mes Playlists', 
    'page.receivedTracks': 'Tracks Reçus',
    'page.chat': 'Messages',
    'page.uploadTrack': 'Uploader un Track',
    'page.noTracks': 'Aucun track',
    'page.noPlaylists': 'Aucune playlist',
    'page.noReceivedTracks': 'Aucun track reçu',
    'page.createPlaylist': 'Créer une Playlist',
    'page.playlistName': 'Nom de la Playlist',
    'page.createPlaylistHint': 'Créez votre première playlist pour organiser vos tracks préférés',
    
    // Upload
    'upload.selectAudio': 'Sélectionner un fichier MP3 ou WAV',
    'upload.selectCover': 'Appuyez pour choisir une pochette',
    'upload.coverExtracted': 'Pochette extraite du MP3',
    'upload.submit': 'Uploader le Track',
    'upload.uploading': 'Upload en cours...',
    'upload.success': 'Track uploadé avec succès !',
    'upload.error': 'Échec de l\'upload',
    'upload.shareMusic': 'Partagez votre musique avec la communauté SPYNNERS',
    'upload.uploadFor': 'Uploader pour le compte de...',
    'upload.searchProducer': 'Rechercher producteur ou label...',
    'upload.coverImage': 'Image de Couverture',
    'upload.squareFormat': 'Format carré recommandé (1:1)',
    'upload.audioFile': 'Fichier Audio',
    'upload.trackInfo': 'Informations du Track',
    'upload.title': 'Titre',
    'upload.artistName': 'Nom de l\'Artiste',
    'upload.labelName': 'Nom du Label',
    'upload.collaborators': 'Collaborateurs',
    'upload.genreTech': 'Genre & Technique',
    'upload.genre': 'Genre',
    'upload.selectGenre': 'Sélectionner le genre',
    'upload.bpm': 'BPM',
    'upload.key': 'Tonalité',
    'upload.energyLevel': 'Niveau d\'Énergie',
    'upload.mood': 'Ambiance',
    'upload.additionalInfo': 'Informations Additionnelles',
    'upload.releaseDate': 'Date de Sortie',
    'upload.description': 'Description',
    'upload.options': 'Options',
    'upload.unreleased': 'Track Non Sorti',
    'upload.unreleasedDesc': 'Ce track n\'est pas encore sorti',
    'upload.vipRequest': 'Demande Track V.I.P.',
    'upload.vipRequestDesc': 'Demande d\'ajout à la collection V.I.P.',
    'upload.legalAgreements': 'Accords Légaux',
    'upload.rightsConfirm': 'Je confirme être le propriétaire ou avoir les droits pour uploader ce track',
    'upload.freeDownload': 'J\'autorise le téléchargement gratuit à des fins promotionnelles sur SPYNNERS',
    'upload.firstTrackHint': 'Uploadez votre premier track pour commencer',
    
    // SPYN
    'spyn.detection': 'DETECTION',
    'spyn.recordSet': 'RECORD SET',
    'spyn.micro': 'Micro',
    'spyn.usbRec': 'USB + Rec',
    'spyn.analyzing': 'Analyse ACRCloud...',
    'spyn.listening': 'Écoute en cours... (10s)',
    'spyn.trackIdentified': 'Track Identifiée!',
    'spyn.newSearch': 'Nouvelle Recherche',
    'spyn.djSetStarted': 'DJ Set Démarré',
    'spyn.djSetEnded': 'DJ Set Terminé',
    'spyn.tracksIdentified': 'Tracks identifiées',
    'spyn.save': 'Sauvegarder',
    'spyn.delete': 'Supprimer',
    'spyn.stop': 'Arrêter',
    'spyn.stopRecording': 'Arrêter l\'enregistrement',
    'spyn.producerNotified': 'Producteur Notifié!',
    'spyn.playingTrack': 'a été notifié que vous jouez sa track!',
    'spyn.djSetComplete': 'DJ Set Terminé',
    'spyn.duration': 'Durée',
    
    // Profile
    'profile.editProfile': 'Modifier le Profil',
    'profile.blackDiamonds': 'Black Diamonds',
    'profile.settings': 'Paramètres',
    'profile.help': 'Aide & Support',
    'profile.terms': 'CGU & Confidentialité',
    'profile.admin': 'Admin Panel',
    'profile.logout': 'Déconnexion',
    'profile.updateInfo': 'Mettre à jour vos informations',
    'profile.buyDiamonds': 'Acheter des diamonds',
    'profile.manageTracks': 'Gérer vos tracks',
    'profile.viewPlaylists': 'Voir vos playlists',
    'profile.visitWebsite': 'Visiter spynners.com',
    'profile.frequentQuestions': 'Questions fréquentes',
    'profile.termsOfUse': 'Conditions d\'utilisation',
    'profile.uploads': 'Uploads',
    'profile.diamonds': 'Diamonds',
    'profile.favorites': 'Favoris',
    'profile.logoutConfirm': 'Voulez-vous vraiment vous déconnecter ?',
    
    // Common
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.search': 'Rechercher',
    'common.noResults': 'Aucun résultat',
    'common.language': 'Langue',
    'common.selectLanguage': 'Sélectionnez votre langue',
    'common.tracks': 'tracks',
    'common.members': 'Membres',
    'common.online': 'En ligne',
    'common.unread': 'Non lus',
    'common.playAll': 'Tout jouer',
    'common.shuffle': 'Aléatoire',
    'common.select': 'Sélectionner',
    
    // Menu items
    'menu.myUploads': 'Mes Uploads',
    'menu.profile': 'Profil',
    'menu.chat': 'Chat',
    'menu.received': 'Reçus',
    'menu.playlists': 'Playlists',
    'menu.analytics': 'Statistiques',
    'menu.rankings': 'Classements',
    'menu.liveRadar': 'Live Radar',
    'menu.vip': 'V.I.P.',
    'menu.uploadTrack': 'Uploader un Track',
    'menu.website': 'Site Web',
    
    // Actions
    'action.download': 'Télécharger',
    'action.share': 'Partager',
    'action.addToPlaylist': 'Ajouter à la Playlist',
    'action.sendTrack': 'Envoyer le Track',
    
    // Filters
    'filter.allGenres': 'Tous les Genres',
    'filter.allEnergy': 'Tous les Niveaux',
    'filter.recentlyAdded': 'Récemment Ajoutés',
    'filter.aToZ': 'A à Z',
    'filter.topRated': 'Mieux Notés',
    'filter.low': 'Bas',
    'filter.medium': 'Moyen',
    'filter.high': 'Haut',
    'filter.vipOnly': 'VIP Seulement',
    'filter.searchPlaceholder': 'Rechercher des tracks...',
    
    // Chat
    'chat.messages': 'Messages',
    'chat.searchMembers': 'Rechercher des membres...',
    'chat.noMembersFound': 'Aucun membre trouvé',
    'chat.loadingMembers': 'Chargement des membres...',
    'chat.noMessages': 'Pas encore de messages',
    'chat.startConversation': 'Dites bonjour pour commencer la conversation!',
    'chat.typeMessage': 'Écrivez un message...',
    
    // Playlist
    'playlist.tracks': 'Tracks',
    'playlist.noTracksInPlaylist': 'Aucun track dans cette playlist',
    'playlist.addTracksHint': 'Ajoutez des tracks depuis l\'accueil',
    'playlist.loadingTracks': 'Chargement des tracks...',
    
    // Library
    'library.myUploads': 'Mes Uploads',
    'library.noUploads': 'Aucun upload',
    'library.uploadFirst': 'Uploadez votre premier track pour commencer',
    'library.status': 'Statut',
    'library.pending': 'En attente',
    'library.approved': 'Approuvé',
    'library.rejected': 'Rejeté',
    
    // Received
    'received.title': 'Tracks Reçus',
    'received.from': 'De',
    'received.noTracks': 'Aucun track reçu',
    'received.waitingTracks': 'Les tracks qui vous sont envoyés apparaîtront ici',
    
    // Diamonds
    'diamonds.yourBalance': 'Votre solde',
    'diamonds.info': 'Les Black Diamonds permettent de télécharger des tracks VIP exclusives et d\'accéder à du contenu premium.',
    'diamonds.buyDiamonds': 'Acheter des Diamonds',
    'diamonds.popular': 'POPULAIRE',
    'diamonds.processing': 'Traitement...',
    'diamonds.buyNow': 'Acheter maintenant',
    'diamonds.vipBenefits': 'Avantages VIP',
    'diamonds.vipDownloads': 'Téléchargements VIP',
    'diamonds.accessExclusive': 'Accédez aux tracks exclusives',
    'diamonds.premiumContent': 'Contenu Premium',
    'diamonds.tracksBeforeEveryone': 'Tracks avant tout le monde',
    'diamonds.supportArtists': 'Soutien aux artistes',
    'diamonds.supportProducers': 'Soutenez les producteurs',
    'diamonds.selectionRequired': 'Sélection requise',
    'diamonds.chooseAPack': 'Choisissez un pack de diamonds',
    'diamonds.confirmPurchase': 'Acheter {amount} Black Diamonds pour {price}?\n\nVous serez redirigé vers spynners.com pour finaliser l\'achat.',
    'diamonds.purchaseComplete': 'Achat terminé! 💎',
    'diamonds.diamondsAdded': '{amount} Black Diamonds ajoutés à votre compte!',
    'diamonds.purchaseError': 'Impossible d\'ouvrir la page d\'achat. Veuillez réessayer.',
    'diamonds.continue': 'Continuer',
    
    // Analytics
    'analytics.title': 'Mes Statistiques',
    'analytics.noTracks': 'Aucun track',
    'analytics.uploadToSee': 'Uploadez des tracks pour voir vos statistiques',
    'analytics.myTracks': 'Mes Tracks',
    'analytics.totalPlays': 'Lectures Totales',
    'analytics.downloads': 'Téléchargements',
    'analytics.avgRating': 'Note Moyenne',
    'analytics.trackStatus': 'Statut des Tracks',
    'analytics.approved': 'Approuvés',
    'analytics.pending': 'En attente',
    
    // Edit Profile
    'edit.title': 'Modifier le Profil',
    'edit.iAmA': 'Je suis...',
    'edit.dj': 'DJ',
    'edit.producer': 'Producteur',
    'edit.both': 'Les deux',
    'edit.label': 'Label',
    'edit.musicLover': 'Mélomane',
    'edit.basicInfo': 'Informations de base',
    'edit.fullName': 'Nom complet',
    'edit.djName': 'Nom de DJ',
    'edit.producerName': 'Nom de producteur',
    'edit.sacemNumber': 'N° Sociétaire SACEM (optionnel)',
    'edit.socialLinks': 'Réseaux Sociaux',
    'edit.saveChanges': 'Enregistrer',
    'edit.saving': 'Enregistrement...',
    
    // Help/FAQ
    'help.title': 'Aide & FAQ',
    'help.frequentQuestions': 'Questions Fréquentes',
    'help.howToDownload': 'Comment télécharger un track ?',
    'help.whatAreDiamonds': 'Que sont les Black Diamonds ?',
    'help.howToUpload': 'Comment uploader un track ?',
    'help.howSpynWorks': 'Comment fonctionne SPYN ?',
    'help.canCreatePlaylists': 'Puis-je créer plusieurs playlists ?',
    'help.howToBecomeProducer': 'Comment devenir producteur sur SPYNNERS ?',
    'help.areTracksFree': 'Les tracks sont-elles gratuites ?',
    'help.contactUs': 'Nous Contacter',
    'help.haveQuestion': 'Une question ?',
    'help.writeMessage': 'Écrivez votre message ici...',
    'help.send': 'Envoyer',
    
    // Terms
    'terms.title': 'Conditions d\'Utilisation',
    'terms.lastUpdate': 'Dernière mise à jour',
    'terms.acceptConditions': 'Acceptation des conditions',
    'terms.serviceDescription': 'Description du service',
    'terms.userAccount': 'Compte utilisateur',
    'terms.userContent': 'Contenu utilisateur',
    'terms.blackDiamonds': 'Black Diamonds',
    
    // Live Radar
    'radar.title': 'Radar Live',
    'radar.activeDjs': 'DJs Actifs',
    'radar.nearYou': 'Près de vous',
    'radar.worldwide': 'Monde entier',
    'radar.noDjsNearby': 'Aucun DJ à proximité',
    'radar.expandSearch': 'Élargissez votre recherche pour trouver plus de DJs',
    'radar.playing': 'Joue',
    'radar.distance': 'Distance',
  },
  
  es: {
    'login.title': 'Iniciar Sesión',
    'login.email': 'Correo',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.signIn': 'Iniciar Sesión',
    'login.noAccount': '¿No tienes cuenta?',
    'login.signUp': 'Registrarse',
    'login.subtitle': 'Free House Music Promo Pool',
    'signup.welcome': '¡Bienvenido a SPYNNERS!',
    'signup.joinCommunity': 'Únete a la mayor comunidad de DJs y productores de House Music',
    'signup.youAre': 'Eres...',
    'signup.continue': 'Continuar',
    'signup.createAccount': 'Crear tu cuenta',
    'signup.fillInfo': 'Completa tu información para unirte a SPYNNERS',
    'signup.fullName': 'Nombre completo / Nombre artístico',
    'signup.labelName': 'Nombre del sello',
    'signup.confirmPassword': 'Confirmar contraseña',
    'signup.acceptTerms': 'Acepto los',
    'signup.termsOfUse': 'términos de uso',
    'signup.and': 'y la',
    'signup.privacyPolicy': 'política de privacidad',
    'signup.createMyAccount': 'Crear mi cuenta',
    'signup.alreadyAccount': '¿Ya tienes cuenta?',
    'signup.change': 'Cambiar',
    'userType.dj': 'DJ',
    'userType.djDesc': 'Toco música en clubs/eventos',
    'userType.producer': 'Productor',
    'userType.producerDesc': 'Produzco música',
    'userType.djProducer': 'DJ & Productor',
    'userType.djProducerDesc': 'Toco y produzco',
    'userType.label': 'Sello',
    'userType.labelDesc': 'Represento un sello musical',
    'nav.home': 'Inicio',
    'nav.library': 'Biblioteca',
    'nav.spyn': 'SPYN',
    'nav.chat': 'Chat',
    'nav.profile': 'Perfil',
    'nav.home': 'Inicio',
    'nav.playlist': 'Playlists',
    'nav.received': 'Recibidos',
    'nav.upload': 'Subir Track',
    
    // SPYN
    'spyn.detection': 'DETECCIÓN',
    'spyn.recordSet': 'GRABAR SET',
    'spyn.micro': 'Micro',
    'spyn.usbRec': 'USB + Rec',
    'spyn.analyzing': 'Analizando con ACRCloud...',
    'spyn.listening': 'Escuchando... (10s)',
    'spyn.trackIdentified': '¡Track Identificado!',
    'spyn.newSearch': 'Nueva Búsqueda',
    'spyn.djSetStarted': 'DJ Set Iniciado',
    'spyn.djSetEnded': 'DJ Set Terminado',
    'spyn.tracksIdentified': 'Tracks identificados',
    'spyn.save': 'Guardar',
    'spyn.delete': 'Eliminar',
    'spyn.stop': 'Parar',
    'spyn.stopRecording': 'Parar Grabación',
    'spyn.producerNotified': '¡Productor Notificado!',
    'spyn.playingTrack': '¡ha sido notificado de que estás reproduciendo su track!',
    'spyn.djSetComplete': 'DJ Set Completado',
    'spyn.duration': 'Duración',
    
    // Profile
    'profile.editProfile': 'Editar Perfil',
    'profile.blackDiamonds': 'Black Diamonds',
    'profile.settings': 'Configuración',
    'profile.help': 'Ayuda & Soporte',
    'profile.terms': 'Términos & Privacidad',
    'profile.admin': 'Panel Admin',
    'profile.logout': 'Cerrar Sesión',
    'profile.updateInfo': 'Actualizar tu información',
    'profile.buyDiamonds': 'Comprar diamonds',
    'profile.manageTracks': 'Gestionar tus tracks',
    'profile.viewPlaylists': 'Ver tus playlists',
    'profile.visitWebsite': 'Visitar spynners.com',
    'profile.frequentQuestions': 'Preguntas frecuentes',
    'profile.termsOfUse': 'Términos de uso',
    'profile.uploads': 'Subidas',
    'profile.diamonds': 'Diamonds',
    'profile.favorites': 'Favoritos',
    'profile.logoutConfirm': '¿Realmente quieres cerrar sesión?',
    
    // Common
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.search': 'Buscar',
    'common.noResults': 'Sin resultados',
    'common.language': 'Idioma',
    'common.selectLanguage': 'Selecciona tu idioma',
    'common.tracks': 'tracks',
    'common.members': 'Miembros',
    'common.online': 'En línea',
    'common.unread': 'No leídos',
    'common.playAll': 'Reproducir Todo',
    'common.shuffle': 'Aleatorio',
    'common.select': 'Seleccionar',
    
    // Page titles
    'page.myUploads': 'Mis Subidas',
    'page.myPlaylists': 'Mis Playlists',
    'page.receivedTracks': 'Tracks Recibidos',
    'page.chat': 'Mensajes',
    'page.uploadTrack': 'Subir Track',
    'page.noTracks': 'Sin tracks todavía',
    'page.noPlaylists': 'Sin playlists todavía',
    'page.noReceivedTracks': 'Sin tracks recibidos',
    'page.createPlaylist': 'Crear Playlist',
    'page.playlistName': 'Nombre de la Playlist',
    'page.createPlaylistHint': 'Crea tu primera playlist para organizar tus tracks favoritos',
    
    // Menu items
    'menu.received': 'Recibidos',
    'menu.myUploads': 'Mis Subidas',
    'menu.profile': 'Perfil',
    'menu.chat': 'Chat',
    'menu.playlists': 'Playlists',
    'menu.analytics': 'Estadísticas',
    'menu.vip': 'V.I.P.',
    'menu.rankings': 'Rankings',
    'menu.liveRadar': 'Radar en Vivo',
    'menu.uploadTrack': 'Subir Track',
    'menu.website': 'Sitio Web',
    
    // Actions
    'action.download': 'Descargar',
    'action.share': 'Compartir',
    'action.addToPlaylist': 'Agregar a Playlist',
    'action.sendTrack': 'Enviar Track',
    
    // Filters
    'filter.allGenres': 'Todos los Géneros',
    'filter.allEnergy': 'Todos los Niveles',
    'filter.recentlyAdded': 'Agregados Recientemente',
    'filter.aToZ': 'A a Z',
    'filter.topRated': 'Mejor Valorados',
    'filter.low': 'Bajo',
    'filter.medium': 'Medio',
    'filter.high': 'Alto',
    'filter.vipOnly': 'Solo VIP',
    'filter.searchPlaceholder': 'Buscar tracks...',
    
    // Upload
    'upload.selectAudio': 'Seleccionar archivo MP3 o WAV',
    'upload.selectCover': 'Toca para seleccionar carátula',
    'upload.coverExtracted': 'Carátula extraída del MP3',
    'upload.submit': 'Subir Track',
    'upload.uploading': 'Subiendo...',
    'upload.success': '¡Track subido exitosamente!',
    'upload.error': 'Error al subir',
    'upload.shareMusic': 'Comparte tu música con la comunidad SPYNNERS',
    'upload.uploadFor': 'Subir para la cuenta de...',
    'upload.searchProducer': 'Buscar productor o sello...',
    'upload.coverImage': 'Imagen de Portada',
    'upload.squareFormat': 'Formato cuadrado recomendado (1:1)',
    'upload.audioFile': 'Archivo de Audio',
    'upload.trackInfo': 'Información del Track',
    'upload.title': 'Título',
    'upload.artistName': 'Nombre del Artista',
    'upload.labelName': 'Nombre del Sello',
    'upload.collaborators': 'Colaboradores',
    'upload.genreTech': 'Género & Técnico',
    'upload.genre': 'Género',
    'upload.selectGenre': 'Seleccionar género',
    'upload.bpm': 'BPM',
    'upload.key': 'Tonalidad',
    'upload.energyLevel': 'Nivel de Energía',
    'upload.mood': 'Ambiente',
    'upload.additionalInfo': 'Información Adicional',
    'upload.releaseDate': 'Fecha de Lanzamiento',
    'upload.description': 'Descripción',
    'upload.options': 'Opciones',
    'upload.unreleased': 'Track No Lanzado',
    'upload.unreleasedDesc': 'Este track aún no ha sido lanzado',
    'upload.vipRequest': 'Solicitud Track V.I.P.',
    'upload.vipRequestDesc': 'Solicitar agregar a la colección V.I.P.',
    'upload.legalAgreements': 'Acuerdos Legales',
    'upload.rightsConfirm': 'Confirmo que soy el propietario o tengo los derechos para subir este track',
    'upload.freeDownload': 'Autorizo la descarga gratuita para fines promocionales en SPYNNERS',
    'upload.firstTrackHint': 'Sube tu primer track para comenzar',
    
    // Chat
    'chat.messages': 'Mensajes',
    'chat.searchMembers': 'Buscar miembros...',
    'chat.noMembersFound': 'No se encontraron miembros',
    'chat.loadingMembers': 'Cargando miembros...',
    'chat.noMessages': 'Sin mensajes todavía',
    'chat.startConversation': '¡Di hola para iniciar la conversación!',
    'chat.typeMessage': 'Escribe un mensaje...',
    
    // Playlist
    'playlist.tracks': 'Tracks',
    'playlist.noTracksInPlaylist': 'Sin tracks en esta playlist',
    'playlist.addTracksHint': 'Agrega tracks desde la pantalla principal',
    'playlist.loadingTracks': 'Cargando tracks...',
    
    // Library
    'library.myUploads': 'Mis Subidas',
    'library.noUploads': 'Sin subidas',
    'library.uploadFirst': 'Sube tu primer track para comenzar',
    'library.status': 'Estado',
    'library.pending': 'Pendiente',
    'library.approved': 'Aprobado',
    'library.rejected': 'Rechazado',
    
    // Received
    'received.title': 'Tracks Recibidos',
    'received.from': 'De',
    'received.noTracks': 'Sin tracks recibidos',
    'received.waitingTracks': 'Los tracks que te envíen aparecerán aquí',
    
    // Diamonds
    'diamonds.yourBalance': 'Tu saldo',
    'diamonds.info': 'Los Black Diamonds permiten descargar tracks VIP exclusivos y acceder a contenido premium.',
    'diamonds.buyDiamonds': 'Comprar Diamonds',
    'diamonds.popular': 'POPULAR',
    'diamonds.processing': 'Procesando...',
    'diamonds.buyNow': 'Comprar ahora',
    'diamonds.vipBenefits': 'Beneficios VIP',
    'diamonds.vipDownloads': 'Descargas VIP',
    'diamonds.accessExclusive': 'Accede a tracks exclusivos',
    'diamonds.premiumContent': 'Contenido Premium',
    'diamonds.tracksBeforeEveryone': 'Tracks antes que nadie',
    'diamonds.supportArtists': 'Apoya a los Artistas',
    'diamonds.supportProducers': 'Apoya a los productores',
    
    // Analytics
    'analytics.title': 'Mis Estadísticas',
    'analytics.noTracks': 'Sin tracks todavía',
    'analytics.uploadToSee': 'Sube tracks para ver tus estadísticas',
    'analytics.myTracks': 'Mis Tracks',
    'analytics.totalPlays': 'Reproducciones Totales',
    'analytics.downloads': 'Descargas',
    'analytics.avgRating': 'Calificación Promedio',
    'analytics.trackStatus': 'Estado de Tracks',
    'analytics.approved': 'Aprobados',
    'analytics.pending': 'Pendientes',
    
    // Edit Profile
    'edit.title': 'Editar Perfil',
    'edit.iAmA': 'Soy...',
    'edit.dj': 'DJ',
    'edit.producer': 'Productor',
    'edit.both': 'Ambos',
    'edit.label': 'Sello',
    'edit.musicLover': 'Amante de la música',
    'edit.basicInfo': 'Información Básica',
    'edit.fullName': 'Nombre Completo',
    'edit.djName': 'Nombre de DJ',
    'edit.producerName': 'Nombre de Productor',
    'edit.sacemNumber': 'N° Sociétaire SACEM (opcional)',
    'edit.socialLinks': 'Redes Sociales',
    'edit.saveChanges': 'Guardar Cambios',
    'edit.saving': 'Guardando...',
    
    // Help/FAQ
    'help.title': 'Ayuda & FAQ',
    'help.frequentQuestions': 'Preguntas Frecuentes',
    'help.howToDownload': '¿Cómo descargar un track?',
    'help.whatAreDiamonds': '¿Qué son los Black Diamonds?',
    'help.howToUpload': '¿Cómo subir un track?',
    'help.howSpynWorks': '¿Cómo funciona SPYN?',
    'help.canCreatePlaylists': '¿Puedo crear múltiples playlists?',
    'help.howToBecomeProducer': '¿Cómo ser productor en SPYNNERS?',
    'help.areTracksFree': '¿Los tracks son gratis?',
    'help.contactUs': 'Contáctanos',
    'help.haveQuestion': '¿Tienes una pregunta?',
    'help.writeMessage': 'Escribe tu mensaje aquí...',
    'help.send': 'Enviar',
    
    // Terms
    'terms.title': 'Términos de Uso',
    'terms.lastUpdate': 'Última actualización',
    'terms.acceptConditions': 'Aceptación de condiciones',
    'terms.serviceDescription': 'Descripción del servicio',
    'terms.userAccount': 'Cuenta de usuario',
    'terms.userContent': 'Contenido del usuario',
    'terms.blackDiamonds': 'Black Diamonds',
    
    // Live Radar
    'radar.title': 'Radar en Vivo',
    'radar.activeDjs': 'DJs Activos',
    'radar.nearYou': 'Cerca de ti',
    'radar.worldwide': 'Todo el mundo',
    'radar.noDjsNearby': 'No hay DJs cerca',
    'radar.expandSearch': 'Amplía tu búsqueda para encontrar más DJs',
    'radar.playing': 'Reproduciendo',
    'radar.distance': 'Distancia',
  },
  
  it: {
    'login.title': 'Accedi',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Password dimenticata?',
    'login.signIn': 'Accedi',
    'login.noAccount': 'Non hai un account?',
    'login.signUp': 'Registrati',
    'login.subtitle': 'Free House Music Promo Pool',
    'signup.welcome': 'Benvenuto su SPYNNERS!',
    'signup.joinCommunity': 'Unisciti alla più grande community di DJ e produttori House Music',
    'signup.youAre': 'Sei...',
    'signup.continue': 'Continua',
    'signup.createAccount': 'Crea il tuo account',
    'signup.fillInfo': 'Compila le tue informazioni per unirti a SPYNNERS',
    'signup.fullName': 'Nome completo / Nome artista',
    'signup.labelName': 'Nome etichetta',
    'signup.confirmPassword': 'Conferma password',
    'signup.acceptTerms': 'Accetto i',
    'signup.termsOfUse': 'termini di utilizzo',
    'signup.and': 'e la',
    'signup.privacyPolicy': 'politica sulla privacy',
    'signup.createMyAccount': 'Crea il mio account',
    'signup.alreadyAccount': 'Hai già un account?',
    'signup.change': 'Modifica',
    'userType.dj': 'DJ',
    'userType.djDesc': 'Suono musica nei club/eventi',
    'userType.producer': 'Produttore',
    'userType.producerDesc': 'Produco musica',
    'userType.djProducer': 'DJ & Produttore',
    'userType.djProducerDesc': 'Suono e produco',
    'userType.label': 'Etichetta',
    'userType.labelDesc': 'Rappresento un\'etichetta musicale',
    'nav.home': 'Home',
    'nav.library': 'Libreria',
    'nav.spyn': 'SPYN',
    'nav.chat': 'Chat',
    'nav.profile': 'Profilo',
    'spyn.detection': 'RILEVAMENTO',
    'spyn.recordSet': 'REGISTRA SET',
    'spyn.micro': 'Micro',
    'spyn.usbRec': 'USB + Rec',
    'spyn.analyzing': 'Analisi ACRCloud...',
    'spyn.listening': 'Ascolto... (10s)',
    'spyn.trackIdentified': 'Track Identificata!',
    'spyn.newSearch': 'Nuova Ricerca',
    'profile.editProfile': 'Modifica Profilo',
    'profile.blackDiamonds': 'Black Diamonds',
    'profile.settings': 'Impostazioni',
    'profile.help': 'Aiuto & Supporto',
    'profile.terms': 'Termini & Privacy',
    'profile.admin': 'Pannello Admin',
    'profile.logout': 'Esci',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.search': 'Cerca',
    'common.noResults': 'Nessun risultato',
    'common.language': 'Lingua',
    'common.selectLanguage': 'Seleziona la tua lingua',
    
    // Menu items
    'menu.received': 'Ricevuti',
    'menu.myUploads': 'I Miei Upload',
    'menu.vip': 'VIP',
    'menu.rankings': 'Classifiche',
    'menu.liveRadar': 'Radar Live',
    'menu.uploadTrack': 'Carica Track',
    
    // Actions
    'action.download': 'Scarica',
    'action.share': 'Condividi',
    'action.addToPlaylist': 'Aggiungi a Playlist',
    'action.sendTrack': 'Invia Track',
    
    // Filters
    'filter.allGenres': 'Tutti i Generi',
    'filter.allEnergy': 'Tutti i Livelli',
    'filter.recentlyAdded': 'Aggiunti di Recente',
    'filter.aToZ': 'A a Z',
    'filter.topRated': 'Più Votati',
    'filter.low': 'Basso',
    'filter.medium': 'Medio',
    'filter.high': 'Alto',
    'filter.vipOnly': 'Solo VIP',
    'filter.searchPlaceholder': 'Cerca tracce...',
  },
  
  de: {
    'login.title': 'Anmelden',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.forgotPassword': 'Passwort vergessen?',
    'login.signIn': 'Anmelden',
    'login.noAccount': 'Noch kein Konto?',
    'login.signUp': 'Registrieren',
    'login.subtitle': 'Free House Music Promo Pool',
    'signup.welcome': 'Willkommen bei SPYNNERS!',
    'signup.joinCommunity': 'Tritt der größten Community von House Music DJs und Produzenten bei',
    'signup.youAre': 'Du bist...',
    'signup.continue': 'Weiter',
    'signup.createAccount': 'Konto erstellen',
    'signup.fillInfo': 'Fülle deine Daten aus, um SPYNNERS beizutreten',
    'signup.fullName': 'Vollständiger Name / Künstlername',
    'signup.labelName': 'Label-Name',
    'signup.confirmPassword': 'Passwort bestätigen',
    'signup.acceptTerms': 'Ich akzeptiere die',
    'signup.termsOfUse': 'Nutzungsbedingungen',
    'signup.and': 'und die',
    'signup.privacyPolicy': 'Datenschutzrichtlinie',
    'signup.createMyAccount': 'Mein Konto erstellen',
    'signup.alreadyAccount': 'Bereits ein Konto?',
    'signup.change': 'Ändern',
    'userType.dj': 'DJ',
    'userType.djDesc': 'Ich lege in Clubs/Events auf',
    'userType.producer': 'Produzent',
    'userType.producerDesc': 'Ich produziere Musik',
    'userType.djProducer': 'DJ & Produzent',
    'userType.djProducerDesc': 'Ich lege auf und produziere',
    'userType.label': 'Label',
    'userType.labelDesc': 'Ich vertrete ein Musiklabel',
    'nav.home': 'Start',
    'nav.library': 'Bibliothek',
    'nav.spyn': 'SPYN',
    'nav.chat': 'Chat',
    'nav.profile': 'Profil',
    'spyn.detection': 'ERKENNUNG',
    'spyn.recordSet': 'SET AUFNEHMEN',
    'spyn.micro': 'Mikro',
    'spyn.usbRec': 'USB + Rec',
    'spyn.analyzing': 'ACRCloud-Analyse...',
    'spyn.listening': 'Höre... (10s)',
    'spyn.trackIdentified': 'Track Identifiziert!',
    'spyn.newSearch': 'Neue Suche',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.blackDiamonds': 'Black Diamonds',
    'profile.settings': 'Einstellungen',
    'profile.help': 'Hilfe & Support',
    'profile.terms': 'AGB & Datenschutz',
    'profile.admin': 'Admin-Panel',
    'profile.logout': 'Abmelden',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.search': 'Suchen',
    'common.noResults': 'Keine Ergebnisse',
    'common.language': 'Sprache',
    'common.selectLanguage': 'Wähle deine Sprache',
    
    // Menu items
    'menu.received': 'Empfangen',
    'menu.myUploads': 'Meine Uploads',
    'menu.vip': 'VIP',
    'menu.rankings': 'Ranglisten',
    'menu.liveRadar': 'Live-Radar',
    'menu.uploadTrack': 'Track hochladen',
    
    // Actions
    'action.download': 'Herunterladen',
    'action.share': 'Teilen',
    'action.addToPlaylist': 'Zur Playlist hinzufügen',
    'action.sendTrack': 'Track senden',
    
    // Filters
    'filter.allGenres': 'Alle Genres',
    'filter.allEnergy': 'Alle Energielevel',
    'filter.recentlyAdded': 'Kürzlich hinzugefügt',
    'filter.aToZ': 'A bis Z',
    'filter.topRated': 'Top bewertet',
    'filter.low': 'Niedrig',
    'filter.medium': 'Mittel',
    'filter.high': 'Hoch',
    'filter.vipOnly': 'Nur VIP',
    'filter.searchPlaceholder': 'Tracks suchen...',
  },
  
  zh: {
    'login.title': '登录',
    'login.email': '邮箱',
    'login.password': '密码',
    'login.forgotPassword': '忘记密码？',
    'login.signIn': '登录',
    'login.noAccount': '还没有账户？',
    'login.signUp': '注册',
    'login.subtitle': '免费House音乐推广池',
    'signup.welcome': '欢迎来到SPYNNERS！',
    'signup.joinCommunity': '加入最大的House音乐DJ和制作人社区',
    'signup.youAre': '你是...',
    'signup.continue': '继续',
    'signup.createAccount': '创建账户',
    'signup.fillInfo': '填写信息加入SPYNNERS',
    'signup.fullName': '全名/艺名',
    'signup.labelName': '厂牌名称',
    'signup.confirmPassword': '确认密码',
    'signup.acceptTerms': '我接受',
    'signup.termsOfUse': '使用条款',
    'signup.and': '和',
    'signup.privacyPolicy': '隐私政策',
    'signup.createMyAccount': '创建我的账户',
    'signup.alreadyAccount': '已有账户？',
    'signup.change': '更改',
    'userType.dj': 'DJ',
    'userType.djDesc': '我在俱乐部/活动中打碟',
    'userType.producer': '制作人',
    'userType.producerDesc': '我制作音乐',
    'userType.djProducer': 'DJ和制作人',
    'userType.djProducerDesc': '我打碟也制作',
    'userType.label': '厂牌',
    'userType.labelDesc': '我代表一个音乐厂牌',
    'nav.home': '首页',
    'nav.library': '音乐库',
    'nav.spyn': 'SPYN',
    'nav.chat': '聊天',
    'nav.profile': '个人资料',
    'spyn.detection': '识别',
    'spyn.recordSet': '录制SET',
    'spyn.micro': '麦克风',
    'spyn.usbRec': 'USB + 录制',
    'spyn.analyzing': 'ACRCloud分析中...',
    'spyn.listening': '聆听中... (10秒)',
    'spyn.trackIdentified': '曲目已识别！',
    'spyn.newSearch': '新搜索',
    'profile.editProfile': '编辑资料',
    'profile.blackDiamonds': '黑钻石',
    'profile.settings': '设置',
    'profile.help': '帮助与支持',
    'profile.terms': '条款与隐私',
    'profile.admin': '管理面板',
    'profile.logout': '退出',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.search': '搜索',
    'common.noResults': '无结果',
    'common.language': '语言',
    'common.selectLanguage': '选择你的语言',
    
    // Menu items
    'menu.received': '已收到',
    'menu.myUploads': '我的上传',
    'menu.vip': 'VIP',
    'menu.rankings': '排行榜',
    'menu.liveRadar': '实时雷达',
    'menu.uploadTrack': '上传曲目',
    
    // Actions
    'action.download': '下载',
    'action.share': '分享',
    'action.addToPlaylist': '添加到播放列表',
    'action.sendTrack': '发送曲目',
    
    // Filters
    'filter.allGenres': '所有风格',
    'filter.allEnergy': '所有能量等级',
    'filter.recentlyAdded': '最近添加',
    'filter.aToZ': 'A到Z',
    'filter.topRated': '最高评分',
    'filter.low': '低',
    'filter.medium': '中',
    'filter.high': '高',
    'filter.vipOnly': '仅VIP',
    'filter.searchPlaceholder': '搜索曲目...',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCurrentFlag: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en'); // Default to English
  const [, forceUpdate] = useState(0); // Force re-render trigger

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem('app_language');
      console.log('[Language] Loaded language from storage:', savedLang);
      if (savedLang && LANGUAGES.some(l => l.code === savedLang)) {
        setLanguageState(savedLang as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    console.log('[Language] Setting language to:', lang);
    try {
      await AsyncStorage.setItem('app_language', lang);
      setLanguageState(lang);
      // Force re-render of all children
      forceUpdate(n => n + 1);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  // Create t function that always uses current language
  const t = (key: string): string => {
    const result = translations[language]?.[key] || translations['en']?.[key] || key;
    return result;
  };

  const getCurrentFlag = (): string => {
    return LANGUAGES.find(l => l.code === language)?.flag || '🇬🇧';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getCurrentFlag }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
